version: "2"
linters:
  enable:
    - containedctx
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - goconst
    - gocritic
    - gomoddirectives
    - gomodguard
    - gosec
    - importas
    - lll
    - misspell
    - nilerr
    - nilnil
    - nonamedreturns
    - prealloc
    - predeclared
    - revive
    - testpackage
    - unconvert
    - unparam
    - wastedassign
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - connector/topologyconnector/generated/
      - extension/settingsproviderextension/generated/
  settings:
    gomoddirectives:
      replace-local: true
      retract-allow-no-explanation: true
    exhaustive:
      # Presence of "default" case in switch statements satisfies exhaustiveness,
      # even if all enum members are not listed.
      # Default: false
      default-signifies-exhaustive: true
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
