mode: deployment
presets:
  kubernetesAttributes:
    enabled: true

config:
  exporters:
    logging: null
    stackstate: {}
  extensions:
    health_check: {}
    memory_ballast: {}
    ingestion_api_key_auth:
      endpoint:
        url: http://localhost:8091/security/ingestion/authorize
      cache:
        valid_size: 2
        valid_ttl: 20s
        invalid_size: 4
  receivers:
    zipkin: null
    jaeger: null
    prometheus: null
    otlp:
      protocols:
        grpc:
          auth:
            authenticator: ingestion_api_key_auth
        http:
          auth:
            authenticator: ingestion_api_key_auth
  processors:
    batch: {}
    memory_limiter: null
    stackstate:
      cluster_name: rancher-rke2-otel-cluster
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [k8sattributes, stackstate, batch, memory_limiter]
        exporters: [stackstate]
      logs: null
      metrics: null

image:
  repository: "ghcr.io/stackvista/sts-opentelemetry-collector"
  tag: main
  pullPolicy: Always

command:
  name: /usr/bin/sts-opentelemetry-collector
